### ISSUE TITLE
Virtualmin Analytics Modules not inserting code - Ubuntu 16.04 PHP 7

### ISSUE THREAD

**Issue by dieskim** [virtualmin/virtualmin-google-analytics#1]
Hi,

I am building some new servers and when adding the Virtualmin Analytics Module I am unable to get it to add the code to the site.

When experimenting I am able to get the code to be added when using the "Preview Website" function:

For Example when viewing the source for

`https:/hostname.com:8443/virtual-server/link.cgi/111.111.11.11/http://www.domain.org/`

I can see

`<script type="text/javascript">var gaJsHost = (("https:" == document.location.protocol) ? "https://ssl." : "http://www."); document.write(unescape("%3Cscript src='" + gaJsHost + "google-analytics.com/ga.js' type='text/javascript'%3E%3C/script%3E")); </script> <script type="text/javascript"> try { var pageTracker = _gat._getTracker("UA-23213123-3"); pageTracker._trackPageview(); } catch(err) { }</script></body>`

But when I just run the domain directly the code is never inserted, I tried running straight via the IP address as well, I also tried other sites, simple index.html pages etc.

I wonder if its because Apache can not execute the Perl CGI script via the domain user?? But I did then go ahead and add a simple Hello Perl Script under

`/home/vdomains/domain.com/cgi-bin/echo.pl`

With Content:
```

#!/usr/bin/perl
use strict;
use warnings;

print qq(Content-type: text/plain\n\n);

print "hi\n";

```
And that works? So I am not sure what is going on...

Any help would be much appreciated

**Comment by jcameron** [comment]
That's very odd, as the preview mode just accesses the same webserver.

Do you perhaps have gzip compression enabled in Apache? If so, try turning it off.

**Comment by dieskim** [comment]
I have disable mod_deflate and still having the same issue...Anything else I can try??

**Comment by dieskim** [comment]
It seems like the preview mode access the webserver via virtualmin and the link.cgi script...I wonder if those are not being run as root/www-data user and then the google-analytics module works rather than when the site it visited directly it runs as the domain owner and then the script does not get run?

**Comment by dieskim** [comment]
Update, I finally did get mod_deflate disabled server wide and the code is now working...is it safe to leave mod_deflate disabled or should I rather just turn off per server or something?

**Comment by dieskim** [comment]
Ok so I left mod_deflate enabled but uncommented everything in /etc/apache2/mods-available/deflate.conf - that way its not actually applying deflate server wide but can be enabled per site if needed

**Comment by dieskim** [comment]
Ok so I see another problem.

Google and Piwik work (I have not tested the others) but head and body script does not work..

I see that they get added in the apache config as below but they never show up on the site

```
PerlRequire /etc/webmin/virtualmin-google-analytics/apachemod.pl
PerlOutputFilterHandler Virtualmin::GoogleAnalytics
PerlSetVar HeadJavascriptFile /etc/webmin/virtualmin-google-analytics/14901733088276.head.js
PerlSetVar BodyJavascriptFile /etc/webmin/virtualmin-google-analytics/14901733088276.body.js
```

**Comment by dieskim** [comment]
OK all the others work as well.

Head and Body only get added IF one of the other analytics variables is set - is that how it is meant to work?

**Comment by jcameron** [comment]
Virtualmin doesn't use `HeadJavascriptFile` though .. instead, the `apachemod.pl` script dynamically alters the HTML to include the analytics scripts in the HEAD or BODY tags.

**Comment by dieskim** [comment]
Those are the lines that get added when I add script in the Head / Body blocks here..

<img width="1114" alt="screen shot 2017-03-27 at 9 29 00 am" src="https://cloud.githubusercontent.com/assets/9603625/24338483/ed6e03d0-12cf-11e7-8601-ce2c7707b6bd.png">

**Comment by jcameron** [comment]
Oh right, that's for adding your own custom additional HTML / JS - I forgot about that feature!

This will be fixed in the next release of the analytics plugin though.
